/**
 * 주문 상태 코드
 */
export const ORDER_STATUS = {
  ALL: 0,
  UNCONFIRMED: 1,
  CONFIRMED: 2,
  SHIPPED: 3,
  COMPLETED: 4,
  CANCELLED: 5
};

/**
 * 주문 상태 텍스트
 */
export const ORDER_STATUS_TEXT = {
  [ORDER_STATUS.ALL]: '전체',
  [ORDER_STATUS.UNCONFIRMED]: '미확인',
  [ORDER_STATUS.CONFIRMED]: '확인',
  [ORDER_STATUS.SHIPPED]: '출고',
  [ORDER_STATUS.COMPLETED]: '완료',
  [ORDER_STATUS.CANCELLED]: '취소'
};

/**
 * 주문 상태 클래스
 */
export const ORDER_STATUS_CLASS = {
  [ORDER_STATUS.ALL]: 'all',
  [ORDER_STATUS.UNCONFIRMED]: 'unconfirm',
  [ORDER_STATUS.CONFIRMED]: 'confirm',
  [ORDER_STATUS.SHIPPED]: 'release',
  [ORDER_STATUS.COMPLETED]: 'complete',
  [ORDER_STATUS.CANCELLED]: 'cancel'
};

/**
 * 주문 상태 옵션 목록 (select 태그용)
 */
export const ORDER_STATUS_OPTIONS = [
  { value: ORDER_STATUS.ALL, label: ORDER_STATUS_TEXT[ORDER_STATUS.ALL] },
  { value: ORDER_STATUS.UNCONFIRMED, label: ORDER_STATUS_TEXT[ORDER_STATUS.UNCONFIRMED] },
  { value: ORDER_STATUS.CONFIRMED, label: ORDER_STATUS_TEXT[ORDER_STATUS.CONFIRMED] },
  { value: ORDER_STATUS.SHIPPED, label: ORDER_STATUS_TEXT[ORDER_STATUS.SHIPPED] },
  { value: ORDER_STATUS.COMPLETED, label: ORDER_STATUS_TEXT[ORDER_STATUS.COMPLETED] },
  { value: ORDER_STATUS.CANCELLED, label: ORDER_STATUS_TEXT[ORDER_STATUS.CANCELLED] }
];

export default {
  STATUS: ORDER_STATUS,
  TEXT: ORDER_STATUS_TEXT,
  CLASS: ORDER_STATUS_CLASS,
  OPTIONS: ORDER_STATUS_OPTIONS
}; 